services:
  db:
    image: mysql:8.0
    container_name: mysql_ride_hailing_PRACTICA
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ride_hailing
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backups:/backups
      - ./schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./data.sql:/docker-entrypoint-initdb.d/2_data.sql
      - ./monitoring/mysql-exporter-user.sql:/docker-entrypoint-initdb.d/3_monitoring_user.sql
      - ./permissions.sql:/docker-entrypoint-initdb.d/4_permissions.sql
      - ./procedures.sql:/docker-entrypoint-initdb.d/3_procedures.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot_password"]
      interval: 10s
      timeout: 5s
      retries: 10

  mysql-exporter:
    image: prom/mysqld-exporter:v0.19.0
    container_name: mysql_exporter_ride_hailing
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      MYSQLD_EXPORTER_PASSWORD: exporter_password
    command:
      - "--mysqld.address=db:3306"
      - "--mysqld.username=exporter"
    ports:
      - "9104:9104"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_ride_hailing
    restart: unless-stopped
    depends_on:
      - mysql-exporter
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_ride_hailing
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning

volumes:
  mysql_data:
  prometheus_data:
  grafana_data: